### ISSUE TITLE
Wine instruction problem

### ISSUE THREAD

**Issue by NeitherPortal** [ish-app/ish#2306]
It’s hard to copy so many lines,so pictures instead.
![IMG_0931](https://github.com/ish-app/ish/assets/139727651/ae79c4b7-d9a0-47e0-ab3b-3b58349de295)

![IMG_0930](https://github.com/ish-app/ish/assets/139727651/b16d02b8-fa06-45cd-8d95-09570e5f6e4b)

**Comment by xloem** [comment]
i think it says `142 illegal instruction at 0x7d40001d: 8e e0 89 e0 8d a4 24 78 `

**Comment by saagarjha** [comment]
`mov    fs,eax`. Hmm, maybe https://github.com/ish-app/ish/commit/3db64777a5ebeb4fbd9255bd141e3055628eb390 helps?

**Comment by xloem** [comment]
@NeitherPortal it looks like the initial part of this issue has been addressed and the testflight build has a chance of working.

**Comment by NeitherPortal** [comment]
Nope,they cannot run wine ,my device is iPhone13,and use the daily build (1.3.3(573))version,still not working.

---- Replied Message ----
| From | ***@***.***> |
| Date | 01/29/2024 07:00 |
| To | ish-app/ish ***@***.***> |
| Cc | NeitherPortal ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ish-app/ish] Wine instruction problem (Issue #2306) |

@NeitherPortal it looks like the initial part of this issue has been addressed and the testflight build has a chance of working.

**Comment by xloem** [comment]
Has the illegal instruction line from the dmesg changed?

**Comment by NeitherPortal** [comment]
No，nothing changed
![IMG_1169](https://github.com/ish-app/ish/assets/139727651/54b66a58-4392-4739-ab13-f06c9e81b7b7)

**Comment by xloem** [comment]
I mean, have the hexadecimal bytes in the dmesg line changed? are they still `8e e0 89 e0 8d a4 24 78`?

**Comment by NeitherPortal** [comment]
Hope that’s what you want 
193 illegal instruction at 0xf7ec3aec: 66 8c e0 83 ec 18 66 89
![IMG_1171](https://github.com/ish-app/ish/assets/139727651/1bbfc074-b9a6-4a51-95d7-e9a6ac67aafd)
![IMG_1172](https://github.com/ish-app/ish/assets/139727651/02c04772-9d50-4a96-8a39-3b5028cb30cf)

**Comment by saagarjha** [comment]
`mov    ax,fs`. I guess it does in fact use fs for something

**Comment by NeitherPortal** [comment]
I am a noob of assembly language,I can only offer you guys the information:(

---- Replied Message ----
| From | Saagar ***@***.***> |
| Date | 02/01/2024 14:15 |
| To | ish-app/ish ***@***.***> |
| Cc | NeitherPortal ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ish-app/ish] Wine instruction problem (Issue #2306) |

mov ax,fs. I guess it does in fact use fs for something
